

const projects = [
  {
    id: 1,
    name: "KnTsT",
    description: "Football Clothes",
    image: "../src/assets/ProjectsImg/kk.png",
    github: "https://github.com/Kheng-Uzamaki/kNTsT-Project",
    demo: "https://test-project-nu-six.vercel.app/",
  },
  {
    id: 2,
    name: "House Marketplace",
    description: "React with Firebase",
    image: "../src/assets/ProjectsImg/house.png",
    github: "https://github.com/Kheng-Uzamaki/house-marketplace",
    demo: "https://houseandroom-marketplace.vercel.app/",
  },
  {
    id: 3,
    name: "Weather",
    description: "Weather API App",
    image: "../src/assets/ProjectsImg/weather.png",
    github: "https://github.com/Kheng-Uzamaki/Kheng-Weather",
    demo: "https://kheng-weather.vercel.app/",
  },
  {
    id: 4,
    name: "ToDo-List",
    description: "ToDo-List App",
    image: "../src/assets/ProjectsImg/todo.png",
    github: "https://github.com/Kheng-Uzamaki/Kheng-ToDo-List",
    demo: "https://kheng-to-do-list.vercel.app/",
  },
  {
    id: 5,
    name: "Quiz App",
    description: "Programming Quiz",
    image: "../src/assets/ProjectsImg/quiz.png",
    github: "https://github.com/Kheng-Uzamaki/QiuzApp",
    demo: "https://qiuz-app-one.vercel.app/",
  },
  {
    id: 6,
    name: "QR Generator",
    description: "QR Generator App",
    image: "../src/assets/ProjectsImg/QR.png",
    github: "https://github.com/Kheng-Uzamaki/QiuzApp",
    demo: "https://qiuz-app-one.vercel.app/",
  },
  {
    id: 7,
    name: "Calculator",
    description: "Calculator Clone App",
    image: "../src/assets/ProjectsImg/calculator.png",
    github: "https://github.com/Kheng-Uzamaki/Caculator",
    demo: "https://calculator-app-zeta-steel.vercel.app/",
  },
  {
    id: 8,
    name: "Note App",
    description: "Noted Clone App",
    image: "../src/assets/ProjectsImg/note.png",
    github: "https://github.com/Kheng-Uzamaki/NoteApp",
    demo: "https://note-app-rose-nine.vercel.app/",
  },
  {
    id: 9,
    name: "Age Calculator",
    description: "Age Calculator App",
    image: "../src/assets/ProjectsImg/age.png",
    github: "https://github.com/Kheng-Uzamaki/AgeCalculator",
    demo: "https://age-calculator-five-theta.vercel.app/",
  },
  {
    id: 10,
    name: "Linkedin",
    description: "Linkedin Clone App",
    image: "../src/assets/ProjectsImg/linked.png",
    github: "https://github.com/Kheng-Uzamaki/linkedin-clone",
    demo: "https://linkedin-clone-alpha-gray.vercel.app/",
  },
  {
    id: 11,
    name: "Social Book",
    description: "Facebook Clone App",
    image: "../src/assets/ProjectsImg/fb.png",
    github: "https://github.com/Kheng-Uzamaki/Social-clone",
    demo: "https://social-clone-sage.vercel.app/",
  },
  {
    id: 12,
    name: "V-Tube",
    description: "Youtube Clone App",
    image: "../src/assets/ProjectsImg/yt.png",
    github: "https://github.com/Kheng-Uzamaki/V-tube",
    demo: "https://v-tube-alpha.vercel.app/",
  },
];

export default projects